transmission:
  image : gfjardim/transmission
  environment:
    - USERNAME=username
    - PASSWORD=password
  volumes:
    - /downloads:/downloads
    - /home/download/transmission:/config
  ports:
    - "9091:9091"

sickbeard:
  image: pabardina/sickbeard-fr
  ports:
   - "8081:8081"
  volumes:
   - /downloads:/downloads
   - /downloads/tv:/tv
   - /home/download/sickbeard:/config
